### ISSUE TITLE
Add vertical/horizontal flipping

### ISSUE THREAD

**Issue by Milkitic** [hawku/TabletDriver#29] opened 2018-03-15 03:45 UTC
Something like wacom's left hand mode for special use

**Comment by Milkitic** [comment] 2018-03-15 04:01
Sorry it's not wacom's features but it's still useful when you flip the screen at same time (retrying some map)

**Comment by SuperTilted** [comment] 2018-03-15 04:33
https://www.reddit.com/r/osugame/comments/83hbiq/testing_different_tablet_drivers_with_a_3d_printer/dvj6mco/

Is this what you're talking about? You should be able to invert the area by inputting 180 deg under rotation.

**Comment by kevinwlau** [comment] 2018-03-15 04:52
Duplicate of #20

**Comment by Shoko84** [comment] 2018-03-15 07:49
I understand it as a "mirroring" thing, is that what you want ?

**Comment by Milkitic** [comment] 2018-03-15 10:06
I help someone asked you to add a feature like Wacom's left hand mode (180 deg), but i forgot it's just a way to rotation, thinking it's something like mirroring the area and added an issue here. After I posted I found the truth but thinking "mirroring" thing can be used anyway: mirror the screen output at same time in some cases. Anyway sorry for misunderstand.

**Comment by hawku** [comment] 2018-03-16 08:30
Duplicate of #20 

[Frequently Asked Questions](https://github.com/hawku/TabletDriver/wiki/FAQ)

**Comment by hawku** [comment] 2018-03-16 08:31
[Frequently Asked Questions](https://github.com/hawku/TabletDriver/wiki/FAQ)

**Closed** 2018-03-16 08:32 UTC
Labels: duplicate
