### ISSUE TITLE
i cant get the top buttons to work

### ISSUE THREAD

**Issue by awesomeboxlord** [hawku/TabletDriver#159] opened 2018-06-01 22:29 UTC
i use the cth-490 and it wont let me program the top buttons

## Hardware/software information
Windows Version: 10 64 bit

Tablet Driver version:the newest one

Tablet model: cth-490

**Comment by hawku** [comment] 2018-08-12 11:07
Duplicate of #33

**Closed** 2018-08-12 11:07 UTC
