### ISSUE TITLE
CTL-471 Connected (Wacom drivers installed) can't use drivers

### ISSUE THREAD

**Issue by anes450** [hawku/TabletDriver#76] opened 2018-03-26 09:38 UTC
Hello everyone.
I tried to install the new drivers (i uninstalled my old wacom drivers) but when i open the GUI, it says that the wacom drivers are installed. I try to customize the area, but the tablet is still in full area, like if it has no drivers.
I completely removed my old wacom drivers from the computer.
What is the problem ?
Thanks

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.3

Tablet model: CTL-471

**Comment by hawku** [comment] 2018-03-26 09:42
Check the issue #1

**Comment by hawku** [comment] 2018-03-26 09:43
Duplicate of #1

**Closed** 2018-03-26 09:43 UTC
