### ISSUE TITLE
32-bit support?

### ISSUE THREAD

**Issue by EddyGam3r** [hawku/TabletDriver#47] opened 2018-03-18 08:28 UTC
The tablet driver doesn't work on 32-bit Windows.

## Hardware/software information
Windows Version: Windows 7 Home Premium 32-bit

Tablet Driver version: Not working

Tablet model: Wacom Intuos Draw CTL490-DW

**Comment by hawku** [comment] 2018-03-18 16:37
Duplicate of #41

**Closed** 2018-03-18 16:37 UTC
Labels: duplicate
