### ISSUE TITLE
Area wacom settings not working properly + Insane cursor movement when leaning my pen.

### ISSUE THREAD

**Issue by Kurumya** [hawku/TabletDriver#85] opened 2018-03-29 18:43 UTC
Hello, I'll try to detail issues i'm facing. 
My wacom program shows these settings with aspect ratio box checked :
Top : 2780 Bottom : 6650  Left : 4077  Right : 9643 
When I write the same config in the gui, it's not the same area at all, and checking aspect ratio won't help. I tried loading my tablets pref but it sets some different numbers which don't correspond at all with my area (distances and top+left are not the same). I tried to move my area in the top left corner to solve the problem and it appears that the force ratio aspect options doesn't apply the same calcul as wacom so the area is moved by 3cm to the bottom and the area is definitively broken. I've tried to set wacom force ratio numbers from filename.wacompref, no force ratio numbers, both with gui force ratio option checked and unchecked, but my area won't correspond to my wacom area.
 May it be caused to my SMALL tablet version? Does this driver only works properly on medium (normal) version of CTL-4X0 ?

The second issue is the most annoying. When I play osu, i'm used to lean my pen to gain speed instead of always moving my arm, but leaning your pen with this driver brokes your cursor so it's not really playable if I don't want to change my playstyle to an only vertical pen moveset :/

Your driver really feels like there is no latency at all and I really want to use it ! I hope future improvements will convince all osu! player to use your driver.

## Hardware/software information
Windows Version:  10 (No fall creators update installed)

Tablet Driver version:  0.13

Tablet model: CTL-480 (Small)

**Comment by RaspberryPi5** [comment] 2018-03-31 15:11
Me too... I'm using the latest version.
my cursor is shaking a lot when I lean my pen.
I always lean my pen when I play osu, so it's so uncomfortable.

Try hawku TabletDriver ver0.0.1.4.
It's much better.

http://hwk.fi/TabletDriver/TabletDriverV0.0.14.zip

**Comment by Kurumya** [comment] 2018-03-31 21:06
I'll try and write a report.

**Comment by Kurumya** [comment] 2018-04-01 11:55
The leaning problem is no longer a problem. The sensation really feels amazing. However, I still have some doubts about my tablet area which, I  think, is not the same between the two drivers. Maybe it's the new feeling brought by this driver that makes me think that...

**Comment by RaspberryPi5** [comment] 2018-04-01 12:19
I hope pen shaking problem will be fixed at the latest driver.
I will just stay at 0.0.1.4 until it is fixed...

**Comment by hawku** [comment] 2018-04-01 18:02
@Kurumya The driver is forcing the tablet area height when you enable the "Force aspect ratio". Wacom drivers might force by the area width depending on what the screen ratio is.

https://github.com/hawku/TabletDriver/wiki/FAQ#q-why-is-the-cursor-shaking
The pen tilt angle should only cause a minor different to the pen signal noise levels (shaking).
I tested tilt angles on my CTH-480 and the noise levels were lower when the pen was touching the tablet's surface at 60 degree angle.

The only way to remove the pen shaking completely is to add more filtering and that causes input lag.
The higher the pen is from the the tablet's surface, the more it would need filtering, so the input latency would have to be much higher.

Check the issue #83
You might have the same hardware problem with your tablet.

@RaspberryPi5  @Kurumya 
CTL-480 should work the same on every version after 0.0.10, so the amount of shaking should be same in the version 0.0.14, 0.1.3 and 0.1.4
Can you test out different versions and tell me in which versions the shaking problem occurs?
I can't reproduce the problem with any of my tablets.

**Comment by RaspberryPi5** [comment] 2018-04-02 09:17
@hawku 0.1.4 latest works perfectly!
Thanks 👍

**Comment by Kurumya** [comment] 2018-04-02 12:11
@hawku 
So how do I get the same exact are ?

**Comment by hawku** [comment] 2018-04-02 14:27
@Kurumya Lets do some simple calculation:
So your old settings are "Top 2780 Bottom : 6650 Left : 4077 Right : 9643".
```
Width = 9643 - 4077 = 5566 = 55.66 mm
Height = 6650 - 2780 = 3870 = 38.70 mm
Aspect ratio = 55.66 mm / 38.70 mm = 1.438
```

If you want the tablet area height to be the same but want the width to match the screen aspect ratio:
```
38.70 * (1920 / 1080) = 38.70 * 1.778 = 68.80 mm
38.70 * (1920 / 1200) = 38.70 * 1.600 = 61.92 mm
```

So if you have set the screen area size as 1920px by 1080px then set the tablet area size to 68.80 mm x 38.70 mm.

**Comment by Kurumya** [comment] 2018-04-02 18:41
My area was 61.92 x 38.70 because my screen is a 1680 x 1050p . Thanks you so much !

**Closed** 2018-04-03 09:04 UTC
