### ISSUE TITLE
Tablet not found (CTL-490)

### ISSUE THREAD

**Issue by doggoboat** [hawku/TabletDriver#38] opened 2018-03-15 21:24 UTC
##Console output

2018-03-15 18:22:59 [INFO] >> # Gaomon S56K
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet "{62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}" 201 HUION_T156
2018-03-15 18:22:59 [ERROR] Can't open USB tablet '{62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}' 201 'HUION_T156'
2018-03-15 18:22:59 [INFO] >> Name "Gaomon S56K"
2018-03-15 18:22:59 [INFO] >> ReportId 0x07
2018-03-15 18:22:59 [INFO] >> ReportLength 8
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x80
2018-03-15 18:22:59 [INFO] >> MaxX 25196
2018-03-15 18:22:59 [INFO] >> MaxY 18896
2018-03-15 18:22:59 [INFO] >> MaxPressure 2047
2018-03-15 18:22:59 [INFO] >> Width 160.0
2018-03-15 18:22:59 [INFO] >> Height 120.0
2018-03-15 18:22:59 [INFO] / End of 'config\tablet.cfg'
2018-03-15 18:22:59 [INFO] >> Include "config\wacom.cfg"
2018-03-15 18:22:59 [INFO] \ Reading 'config\wacom.cfg'
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # This file is automatically generated from these sources:
2018-03-15 18:22:59 [INFO] >> # https://github.com/torvalds/linux/blob/master/drivers/hid/wacom_wac.c
2018-03-15 18:22:59 [INFO] >> # https://github.com/linuxwacom/input-wacom/wiki/Device-IDs
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom PTH-451
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x0314 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x0314 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x0314 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x0314 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom PTH-451"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 31496
2018-03-15 18:22:59 [INFO] >> MaxY 19685
2018-03-15 18:22:59 [INFO] >> MaxPressure 2047
2018-03-15 18:22:59 [INFO] >> Width 157.480
2018-03-15 18:22:59 [INFO] >> Height 98.425
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> Type WacomIntuos
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom PTH-651
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x0315 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x0315 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x0315 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x0315 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom PTH-651"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 44704
2018-03-15 18:22:59 [INFO] >> MaxY 27940
2018-03-15 18:22:59 [INFO] >> MaxPressure 2047
2018-03-15 18:22:59 [INFO] >> Width 223.520
2018-03-15 18:22:59 [INFO] >> Height 139.700
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> Type WacomIntuos
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom PTH-851
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x0317 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x0317 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x0317 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x0317 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom PTH-851"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 65024
2018-03-15 18:22:59 [INFO] >> MaxY 40640
2018-03-15 18:22:59 [INFO] >> MaxPressure 2047
2018-03-15 18:22:59 [INFO] >> Width 325.120
2018-03-15 18:22:59 [INFO] >> Height 203.200
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> Type WacomIntuos
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-460
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x00D4 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x00D4 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x00D4 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x00D4 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-460"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 14720
2018-03-15 18:22:59 [INFO] >> MaxY 9200
2018-03-15 18:22:59 [INFO] >> MaxPressure 1023
2018-03-15 18:22:59 [INFO] >> Width 147.200
2018-03-15 18:22:59 [INFO] >> Height 92.000
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-470
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x00DD 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x00DD 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x00DD 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x00DD 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-470"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 14720
2018-03-15 18:22:59 [INFO] >> MaxY 9200
2018-03-15 18:22:59 [INFO] >> MaxPressure 1023
2018-03-15 18:22:59 [INFO] >> Width 147.200
2018-03-15 18:22:59 [INFO] >> Height 92.000
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-471
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x0300 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x0300 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x0300 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x0300 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-471"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 14720
2018-03-15 18:22:59 [INFO] >> MaxY 9225
2018-03-15 18:22:59 [INFO] >> MaxPressure 1023
2018-03-15 18:22:59 [INFO] >> Width 147.200
2018-03-15 18:22:59 [INFO] >> Height 92.250
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-472
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x037A 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x037A 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x037A 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x037A 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-472"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 15200
2018-03-15 18:22:59 [INFO] >> MaxY 9500
2018-03-15 18:22:59 [INFO] >> MaxPressure 2047
2018-03-15 18:22:59 [INFO] >> Width 152.000
2018-03-15 18:22:59 [INFO] >> Height 95.000
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-480
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x030E 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x030E 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x030E 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x030E 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-480"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 15200
2018-03-15 18:22:59 [INFO] >> MaxY 9500
2018-03-15 18:22:59 [INFO] >> MaxPressure 1023
2018-03-15 18:22:59 [INFO] >> Width 152.000
2018-03-15 18:22:59 [INFO] >> Height 95.000
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-490
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x033B 0x000D 0x0001
2018-03-15 18:22:59 [INFO] Tablet open!
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x033B 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-490"
2018-03-15 18:22:59 [INFO] Tablet name = 'Wacom CTL-490'
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] Tablet report length = 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] Tablet button mask = 40
2018-03-15 18:22:59 [INFO] >> MaxX 15200
2018-03-15 18:22:59 [INFO] Tablet max X = 15200
2018-03-15 18:22:59 [INFO] >> MaxY 9500
2018-03-15 18:22:59 [INFO] Tablet max Y = 9500
2018-03-15 18:22:59 [INFO] >> MaxPressure 2047
2018-03-15 18:22:59 [INFO] Tablet max pressure = 2047
2018-03-15 18:22:59 [INFO] >> Width 152.000
2018-03-15 18:22:59 [INFO] Tablet width = 152.00 mm
2018-03-15 18:22:59 [INFO] >> Height 95.000
2018-03-15 18:22:59 [INFO] Tablet height = 95.00 mm
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] Tablet init feature report: { 0x02, 0x02 }
2018-03-15 18:22:59 [INFO] >> Type WacomIntuos
2018-03-15 18:22:59 [INFO] Tablet type = 1
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-660
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x00D5 0x000D 0x0001
2018-03-15 18:22:59 [INFO] Tablet is already defined!
2018-03-15 18:22:59 [INFO] / End of 'config\wacom.cfg'
2018-03-15 18:22:59 [INFO] >> CheckTablet
2018-03-15 18:22:59 [INFO] >> Include "config\user.cfg"
2018-03-15 18:22:59 [INFO] \ Reading 'config\user.cfg'
2018-03-15 18:22:59 [INFO] / End of 'config\user.cfg'
2018-03-15 18:22:59 [INFO] >> Log Off
2018-03-15 18:22:59 [INFO] Logging stopped!
2018-03-15 18:22:59 [INFO] >> LogDirect false
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x037A 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x037A 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x037A 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-472"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 15200
2018-03-15 18:22:59 [INFO] >> MaxY 9500
2018-03-15 18:22:59 [INFO] >> MaxPressure 2047
2018-03-15 18:22:59 [INFO] >> Width 152.000
2018-03-15 18:22:59 [INFO] >> Height 95.000
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-480
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x030E 0x000D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x030E 0x000D 0x0001
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x030E 0xFF0D 0x0001
2018-03-15 18:22:59 [ERROR] Can't open HID tablet 0x056A 0x030E 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-480"
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] >> MaxX 15200
2018-03-15 18:22:59 [INFO] >> MaxY 9500
2018-03-15 18:22:59 [INFO] >> MaxPressure 1023
2018-03-15 18:22:59 [INFO] >> Width 152.000
2018-03-15 18:22:59 [INFO] >> Height 95.000
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-490
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x033B 0x000D 0x0001
2018-03-15 18:22:59 [INFO] Tablet open!
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x033B 0xFF0D 0x0001
2018-03-15 18:22:59 [INFO] >> Name "Wacom CTL-490"
2018-03-15 18:22:59 [INFO] Tablet name = 'Wacom CTL-490'
2018-03-15 18:22:59 [INFO] >> ReportLength 10
2018-03-15 18:22:59 [INFO] Tablet report length = 10
2018-03-15 18:22:59 [INFO] >> ButtonMask 0x40
2018-03-15 18:22:59 [INFO] Tablet button mask = 40
2018-03-15 18:22:59 [INFO] >> MaxX 15200
2018-03-15 18:22:59 [INFO] Tablet max X = 15200
2018-03-15 18:22:59 [INFO] >> MaxY 9500
2018-03-15 18:22:59 [INFO] Tablet max Y = 9500
2018-03-15 18:22:59 [INFO] >> MaxPressure 2047
2018-03-15 18:22:59 [INFO] Tablet max pressure = 2047
2018-03-15 18:22:59 [INFO] >> Width 152.000
2018-03-15 18:22:59 [INFO] Tablet width = 152.00 mm
2018-03-15 18:22:59 [INFO] >> Height 95.000
2018-03-15 18:22:59 [INFO] Tablet height = 95.00 mm
2018-03-15 18:22:59 [INFO] >> InitFeature 0x02 0x02
2018-03-15 18:22:59 [INFO] Tablet init feature report: { 0x02, 0x02 }
2018-03-15 18:22:59 [INFO] >> Type WacomIntuos
2018-03-15 18:22:59 [INFO] Tablet type = 1
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> # Wacom CTL-660
2018-03-15 18:22:59 [INFO] >> #
2018-03-15 18:22:59 [INFO] >> Tablet 0x056A 0x00D5 0x000D 0x0001
2018-03-15 18:22:59 [INFO] Tablet is already defined!
2018-03-15 18:22:59 [INFO] / End of 'config\wacom.cfg'
2018-03-15 18:22:59 [INFO] >> CheckTablet
2018-03-15 18:22:59 [INFO] >> Include "config\user.cfg"
2018-03-15 18:22:59 [INFO] \ Reading 'config\user.cfg'
2018-03-15 18:22:59 [INFO] / End of 'config\user.cfg'
2018-03-15 18:22:59 [INFO] >> Log Off
2018-03-15 18:22:59 [INFO] Logging stopped!
2018-03-15 18:22:59 [INFO] >> LogDirect false
2018-03-15 18:22:59 [INFO] Log direct print = False
2018-03-15 18:22:59 [INFO] / End of 'config/init.cfg'
2018-03-15 18:22:59 [INFO] >> DesktopSize 2966 900
2018-03-15 18:22:59 [INFO] Desktop size = (2966.00 px x 900.00 px)
2018-03-15 18:22:59 [INFO] >> ScreenArea 2966 900 0 0
2018-03-15 18:22:59 [INFO] Screen area = (w=2966.00, h=900.00, x=0.00, y=0.00)
2018-03-15 18:22:59 [INFO] >> Area 75.12 40.46 79.49 34.3
2018-03-15 18:22:59 [INFO] Tablet area: (75.12 mm x 40.46 mm X+79.49 mm Y+34.30 mm)
2018-03-15 18:22:59 [INFO] >> Rotate 0
2018-03-15 18:22:59 [INFO] Rotation matrix = [1.000000,-0.000000,0.000000,1.000000]
2018-03-15 18:22:59 [INFO] >> Mode Absolute
2018-03-15 18:22:59 [INFO] Output Mode = Absolute
2018-03-15 18:22:59 [INFO] >> ButtonMap 1 2 3
2018-03-15 18:22:59 [INFO] Button Map = 1 2 3 0 0 0 0 0 
2018-03-15 18:22:59 [INFO] >> Filter 0
2018-03-15 18:22:59 [INFO] Tablet filter = off
2018-03-15 18:22:59 [INFO] >> info
2018-03-15 18:22:59 [INFO] 
2018-03-15 18:22:59 [INFO] Tablet: Wacom CTL-490
2018-03-15 18:22:59 [INFO]   Width = 152.00 mm
2018-03-15 18:22:59 [INFO]   Height = 95.00 mm
2018-03-15 18:22:59 [INFO]   Max X = 15200
2018-03-15 18:22:59 [INFO]   Max Y = 9500
2018-03-15 18:22:59 [INFO]   Max Pressure = 2047
2018-03-15 18:22:59 [INFO]   Click Pressure = 0
2018-03-15 18:22:59 [INFO]   Report Id = 00
2018-03-15 18:22:59 [INFO]   Report Length = 10
2018-03-15 18:22:59 [INFO]   Button Mask = 0x40
2018-03-15 18:22:59 [INFO]   Button Map = 1 2 3 0 0 0 0 0 
2018-03-15 18:22:59 [INFO]   Tablet init feature report: { 0x02, 0x02 }
2018-03-15 18:22:59 [INFO] 
2018-03-15 18:22:59 [INFO] Area:
2018-03-15 18:22:59 [INFO]   Desktop = 2966px x 900px
2018-03-15 18:22:59 [INFO]   Screen Map = 2966px x 900px @ X+0px, Y+0px
2018-03-15 18:22:59 [INFO]   Tablet =  75.12mm x 40.46mm @ Min(79.49mm, 34.30mm) Max(154.61mm, 74.76mm)
2018-03-15 18:22:59 [INFO]   Rotation matrix = [1.000000,-0.000000,0.000000,1.000000]
2018-03-15 18:22:59 [INFO] 
2018-03-15 18:22:59 [ERROR] Tablet init failed!
2018-03-15 18:22:59 [ERROR] Possible fixes:
2018-03-15 18:22:59 [ERROR] 1) Uninstall other tablet drivers.
2018-03-15 18:22:59 [ERROR] 2) Stop other tablet driver services.
Driver stopped. Restarting!

## Hardware/software information
Windows Version: 
Windows 10 Home Single Language Version 1703

Tablet Driver version: 
0.0.14

Tablet model: 
CTL490DW

Already tried both fixes given by the console.

**Comment by hawku** [comment] 2018-03-16 08:40
Duplicate of #1

**Closed by hawku** 2018-03-16 08:40 UTC
