### ISSUE TITLE
Tablet not found

### ISSUE THREAD

**Issue by Hashiko225** [hawku/TabletDriver#16] opened 2018-03-14 00:09 UTC
https://gyazo.com/63da4eeb00acb07966c845a9c1b83b6a

**Comment by Shoko84** [comment] 2018-03-14 00:27
Just copying pasta from another issue :

> Add these lines to the Commands tab's first field and press Apply:
> 
> - log debug.txt
> - debug 1
> 
> That should create a debug.txt log file which contains lots of tablet status information.
> Try to reproduce the issue when the debug log is running.
> Log file will be huge if you play too long with logging enabled, but the log file will be cleared every time you apply or save settings.
> When you have captured the issue, close the GUI without saving or applying, zip the log file and upload it here.

Also, on which OS are you ? Which TabletDriver's version are you using ? This can be helpful to help out and fix your issue

**Comment by TuckieO** [comment] 2018-03-14 02:58
I have the same issue and got a log file so Imma piggy back if that's ok? https://puu.sh/zHapo.png
[startuplogT.zip](https://github.com/hawku/TabletDriver/files/1809413/startuplogT.zip)

**Comment by hawku** [comment] 2018-03-16 08:37
Duplicate of #1

**Closed** 2018-03-16 08:37 UTC
